### ISSUE TITLE
state - unknown

### ISSUE THREAD

**Issue by IanAdd** [Hellowlol/ha-tide#3]
## Version of the custom_component

1b972a3
## Configuration

```yaml
- platform: tide
  latitude: -33.722559
  longitude: 151.299201
Add your logs here.

```

## Describe the bug
The Developer Tools 'states' page shows the sensor's state as 'unknown'.

A possible relevance is that my latitude is negative.
The entity name created is: sensor.tide_33_722559_151_299201
The friendly name is: tide_-33_722559_151_299201

## Debug log

The log shows:

Position outside area
8:31:13 PM – custom_components/tide/sensor.py (WARNING)

```text

Add your logs here.

```
